version: '3'
services:

  zk:
    image: zookeeper:3.4.10
    container_name: zk
    restart: on-failure
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    container_name: kafka
    restart: on-failure
    ports:
      - "9092:9092"
    depends_on:
      - zk
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9094,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://:9094,OUTSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

  jaeger:
    image: jaegertracing/all-in-one:1.18.1
    container_name: jaeger
    restart: on-failure
    ports:
      - 5775:5775/udp # agent - accept zipkin.thrift over compact thrift protocol (deprecated, used by legacy clients only)
      - 6831:6831/udp # agent - accept jaeger.thrift over compact thrift protocol
      - 6832:6832/udp # agent - accept jaeger.thrift over binary thrift protocol
      - 5778:5778     # agent - serve configs
      - 16686:16686   # serve frontend
      - 14268:14268   # collector - accept jaeger.thrift directly from clients
      - 14250:14250   # collector - accept model.proto
      - 9411:9411     # collector - Zipkin compatible endpoint (optional)
